# ============================================================================
# Ansible Inventory (YAML Format)
# ============================================================================
# Auto-generated by Terraform - DO NOT EDIT MANUALLY
# Re-generate with: cd terraform && make inventory
# ============================================================================

all:
  children:
    proxmox_hosts:
      children:
%{ if length(lxc_hostnames) > 0 ~}
        lxc_containers:
          hosts:
%{ for hostname in lxc_hostnames ~}
            ${hostname}:
              ansible_host: ${all_hosts[hostname].ansible_host}
              ansible_user: ${all_hosts[hostname].ansible_user}
              ansible_ssh_private_key_file: ${all_hosts[hostname].ansible_ssh_private_key_file}
              ansible_python_interpreter: /usr/bin/python3
%{ endfor ~}
%{ endif ~}
%{ if length(linux_vm_hostnames) > 0 ~}
        linux_vms:
          hosts:
%{ for hostname in linux_vm_hostnames ~}
            ${hostname}:
              ansible_host: ${all_hosts[hostname].ansible_host}
              ansible_user: ${all_hosts[hostname].ansible_user}
              ansible_ssh_private_key_file: ${all_hosts[hostname].ansible_ssh_private_key_file}
              ansible_python_interpreter: /usr/bin/python3
%{ endfor ~}
%{ endif ~}
%{ if length(windows_vm_hostnames) > 0 ~}
        windows_vms:
          hosts:
%{ for hostname in windows_vm_hostnames ~}
            ${hostname}:
              ansible_host: ${all_hosts[hostname].ansible_host}
              ansible_user: ${all_hosts[hostname].ansible_user}
              ansible_ssh_private_key_file: ${all_hosts[hostname].ansible_ssh_private_key_file}
              ansible_connection: ${try(all_hosts[hostname].ansible_connection, "winrm")}
              ansible_port: ${try(all_hosts[hostname].ansible_port, 5985)}
              ansible_winrm_transport: ${try(all_hosts[hostname].ansible_winrm_transport, "basic")}
              ansible_winrm_server_cert_validation: ${try(all_hosts[hostname].ansible_winrm_server_cert_validation, "ignore")}
%{ endfor ~}
%{ endif ~}
