# ============================================================================
# Ansible Inventory - K3s Cluster (YAML Format)
# ============================================================================
# Auto-generated by Terraform - DO NOT EDIT MANUALLY
# Re-generate with: cd terraform/linux-vms && terraform apply
# ============================================================================

all:
  children:
    k3s_cluster:
      children:
%{ if length(k3s_master_hostnames) > 0 ~}
        masters:
          hosts:
%{ for hostname in k3s_master_hostnames ~}
            ${hostname}:
              ansible_host: ${all_hosts[hostname].ansible_host}
              ansible_user: ${all_hosts[hostname].ansible_user}
              ansible_ssh_private_key_file: ${all_hosts[hostname].ansible_ssh_private_key_file}
              ansible_python_interpreter: /usr/bin/python3
%{ endfor ~}
%{ endif ~}
%{ if length(k3s_worker_hostnames) > 0 ~}
        workers:
          hosts:
%{ for hostname in k3s_worker_hostnames ~}
            ${hostname}:
              ansible_host: ${all_hosts[hostname].ansible_host}
              ansible_user: ${all_hosts[hostname].ansible_user}
              ansible_ssh_private_key_file: ${all_hosts[hostname].ansible_ssh_private_key_file}
              ansible_python_interpreter: /usr/bin/python3
%{ endfor ~}
%{ endif ~}

