#!/usr/bin/env bash
# Setup script for GitLab backend authentication
set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${CYAN}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║  Terraform GitLab Backend Authentication Setup           ║${NC}"
echo -e "${CYAN}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check if token is provided as argument
if [ $# -eq 1 ]; then
    GITLAB_TOKEN="$1"
    echo -e "${GREEN}✓ Using token from command line argument${NC}"
else
    echo -e "${YELLOW}📝 Enter your GitLab Personal Access Token:${NC}"
    echo -e "${CYAN}   (Get it from: https://gitlab.example.com/-/user_settings/personal_access_tokens)${NC}"
    echo -e "${CYAN}   Required scopes: api, read_api, write_repository${NC}"
    echo ""
    read -rsp "Token: " GITLAB_TOKEN
    echo ""
fi

# Validate token format
if [[ ! "$GITLAB_TOKEN" =~ ^gitlab-token- ]]; then
    echo -e "${RED}✗ Invalid token format. GitLab tokens should start with 'gitlab-token-'${NC}"
    exit 1
fi

# Create backend.secrets.tfvars in each terraform directory
DIRS=("lxc" "linux-vms" "windows-vms" "talos-vms")

for dir in "${DIRS[@]}"; do
    if [ -d "$dir" ]; then
        SECRETS_FILE="$dir/backend.secrets.tfvars"

        cat > "$SECRETS_FILE" <<EOF
# Backend Authentication Secrets
# Auto-generated by setup-backend-auth.sh
# DO NOT COMMIT THIS FILE!

# GitLab Personal Access Token
password = "$GITLAB_TOKEN"
EOF

        chmod 600 "$SECRETS_FILE"
        echo -e "${GREEN}✓ Created: $SECRETS_FILE${NC}"
    else
        echo -e "${YELLOW}⚠ Skipped: $dir (directory not found)${NC}"
    fi
done

echo ""
echo -e "${GREEN}✅ Backend authentication configured successfully!${NC}"
echo ""
echo -e "${CYAN}Next steps:${NC}"
echo -e "  1. cd into any terraform directory (lxc, linux-vms, windows-vms)"
echo -e "  2. Run: ${GREEN}make init${NC}"
echo -e "  3. Terraform will use backend.secrets.tfvars automatically"
echo ""
echo -e "${YELLOW}Security note:${NC}"
echo -e "  - backend.secrets.tfvars is in .gitignore"
echo -e "  - File permissions set to 600 (owner read/write only)"
echo -e "  - Never commit this file to git!"
echo ""
