# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# Provider configuration
# Generated by Terragrunt root.hcl — do not edit manually

provider "proxmox" {
  endpoint  = replace(var.proxmox_api_url, "/api2/json", "")
  api_token = "${var.proxmox_api_token_id}=${var.proxmox_api_token_secret}"
  insecure  = true

  ssh {
    agent = true
  }
}
