# ============================================================================
# Terragrunt Root Configuration
# ============================================================================
# This file is the DRY root inherited by all units via:
#   include "root" { path = find_in_parent_folders("root.hcl") }
#
# It generates three files in each unit's working directory:
#   - backend.tf   (Cloudflare R2 S3-compatible remote state)
#   - versions.tf  (required_version + required_providers)
#   - provider.tf  (Proxmox provider configuration)
#
# State key is derived automatically from the unit's directory name
# relative to this root.hcl, e.g. "linux-vms/terraform.tfstate".
# ============================================================================

remote_state {
  backend = "s3"

  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }

  config = {
    bucket = "terraform-state"

    # Automatically derive the state key from the unit's directory path.
    # e.g. for terraform/linux-vms/ → "linux-vms/terraform.tfstate"
    key = "${path_relative_to_include()}/terraform.tfstate"

    # Cloudflare R2 S3-compatible endpoint
    endpoints = {
      s3 = "https://04376f2b0f3e66492fef38704902782b.r2.cloudflarestorage.com"
    }

    region  = "auto"
    profile = "r2-terraform"

    # Required for S3-compatible endpoints (no AWS signature region enforcement)
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
    skip_requesting_account_id  = true

    # R2 does not support state locking natively
    use_lockfile = false
  }
}

# Generate versions.tf in each unit's working directory
generate "versions" {
  path      = "versions.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
# Terraform version requirements
# Generated by Terragrunt root.hcl — do not edit manually

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    proxmox = {
      source  = "bpg/proxmox"
      version = "~> 0.98"
    }

    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.1"
    }

    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}
EOF
}

# Generate provider.tf in each unit's working directory
generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
# Provider configuration
# Generated by Terragrunt root.hcl — do not edit manually

provider "proxmox" {
  endpoint  = replace(var.proxmox_api_url, "/api2/json", "")
  api_token = "$${var.proxmox_api_token_id}=$${var.proxmox_api_token_secret}"
  insecure  = true

  ssh {
    agent = true
  }
}
EOF
}
