# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# Terraform version requirements
# Generated by Terragrunt root.hcl — do not edit manually

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    proxmox = {
      source  = "bpg/proxmox"
      version = "~> 0.98"
    }

    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.1"
    }

    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}
