---
# AdGuard Home DNS Server (adguard-1) Service Metadata
# This file is used by the GitLab CI/CD pipeline for automated deployment

# [REQUIRED] Deployment Target
# Maps to GitLab CI secrets: ENV_ADGUARD_1, HOST_ADGUARD_1, SSH_KEY_ADGUARD_1
target_host: adguard-1
