#!/bin/bash

###############################################################################
# Dynamic Resource Calculation for Unbound DNS Server
###############################################################################

# Get cache percentage from environment variable (default: 40%)
cache_percentage=${UNBOUND_CACHE_PERCENTAGE:-40}

# Validate cache percentage is numeric and within range
if ! [[ "$cache_percentage" =~ ^[0-9]+$ ]] || [ "$cache_percentage" -lt 1 ] || [ "$cache_percentage" -gt 90 ]; then
    echo "Invalid UNBOUND_CACHE_PERCENTAGE=${cache_percentage} (must be 1-90). Using default: 40" >&2
    cache_percentage=40
fi

# Detect available memory
availableMemory=$((1024 * $( (grep MemAvailable /proc/meminfo || grep MemTotal /proc/meminfo) | sed 's/[^0-9]//g' ) ))
memoryLimit=$availableMemory

# Check cgroup memory limit (for containers)
# cgroup v2 (modern kernels, Debian Trixie default)
if [ -r /sys/fs/cgroup/memory.max ]; then
    cgroupLimit=$(cat /sys/fs/cgroup/memory.max)
    # cgroup v2 uses "max" for unlimited
    if [ "$cgroupLimit" != "max" ]; then
        memoryLimit="${cgroupLimit//[!0-9]/}"
    fi
# cgroup v1 (legacy)
elif [ -r /sys/fs/cgroup/memory/memory.limit_in_bytes ]; then
    cgroupLimit=$(cat /sys/fs/cgroup/memory/memory.limit_in_bytes | sed 's/[^0-9]//g')
    # cgroup v1 uses max int64 (9223372036854775807) for unlimited
    if [ "$cgroupLimit" -lt 9223372036854775807 ] 2>/dev/null; then
        memoryLimit=$cgroupLimit
    fi
fi
[[ ! -z $memoryLimit && $memoryLimit -gt 0 && $memoryLimit -lt $availableMemory ]] && availableMemory=$memoryLimit

# Calculate reserved memory (10% of total, minimum 256MB)
reserved_mb=$((memoryLimit / 1024 / 1024 / 10))
[[ $reserved_mb -lt 256 ]] && reserved_mb=256
reserved=$((reserved_mb * 1024 * 1024))

# Ensure minimum memory requirement
if [ "$availableMemory" -le $((reserved * 2)) ]; then
    echo "Not enough memory available. Need at least $((reserved * 2 / 1024 / 1024))MB" >&2
    exit 1
fi

# Calculate total cache budget
available_after_reserved=$((availableMemory - reserved))
total_cache=$((available_after_reserved * cache_percentage / 100))

# Distribute cache among 4 types (DNSSEC-validating, DoT-forwarding resolver).
# Docs recommend rrset ~= 2x msg; the negative cache is enlarged because
# aggressive-nsec synthesises negative answers from cached NSEC records.
# rrset: 50%  msg: 25%  key: 10%  neg: 15%
rrset_cache=$((total_cache * 50 / 100))
msg_cache=$((total_cache / 4))
key_cache=$((total_cache * 10 / 100))
neg_cache=$((total_cache * 15 / 100))

# Convert to MB for Unbound config
rrset_cache_mb=$((rrset_cache / 1024 / 1024))
msg_cache_mb=$((msg_cache / 1024 / 1024))
key_cache_mb=$((key_cache / 1024 / 1024))
neg_cache_mb=$((neg_cache / 1024 / 1024))

# Ensure minimum cache sizes
[[ $rrset_cache_mb -lt 16 ]] && rrset_cache_mb=16
[[ $msg_cache_mb -lt 8 ]] && msg_cache_mb=8
[[ $key_cache_mb -lt 8 ]] && key_cache_mb=8
[[ $neg_cache_mb -lt 4 ]] && neg_cache_mb=4

# Thread calculation - use all CPUs for dedicated DNS container
cpu_count=$(nproc)
threads=${UNBOUND_THREADS:-$cpu_count}

# Slab calculation - must be power of 2, close to thread count
if [ "$threads" -gt 1 ]; then
    slabs=1
    while [ $((slabs * 2)) -le "$threads" ]; do
        slabs=$((slabs * 2))
    done
else
    slabs=1
fi

# Log calculated values
echo "==================================================================="
echo "Unbound Dynamic Configuration"
echo "==================================================================="
echo "Container Memory:    $((memoryLimit / 1024 / 1024)) MB"
echo "Reserved Memory:     ${reserved_mb} MB"
echo "Cache Percentage:    ${cache_percentage}%"
echo "Total Cache Budget:  $((total_cache / 1024 / 1024)) MB"
echo "-------------------------------------------------------------------"
echo "Cache Allocation:"
echo "  - RRset Cache:     ${rrset_cache_mb} MB (50%)"
echo "  - Message Cache:   ${msg_cache_mb} MB (25%)"
echo "  - Key Cache:       ${key_cache_mb} MB (10%)"
echo "  - Negative Cache:  ${neg_cache_mb} MB (15%)"
echo "-------------------------------------------------------------------"
echo "CPU Configuration:"
echo "  - Threads:         ${threads}"
echo "  - Slabs:           ${slabs}"
echo "==================================================================="

# Write the resource-tuned values consumed by unbound.conf via:
#   include: "/opt/unbound/etc/unbound/dynamic.conf"
# unbound.conf itself is a static, version-controlled file (baked into the
# image and/or bind-mounted), so we always (re)generate only dynamic.conf here
# to pick up changes in container memory/CPU on restart.
cat > /opt/unbound/etc/unbound/dynamic.conf << EOT
# Generated by unbound.sh at container start - do not edit by hand.
# Included inside the server: clause of unbound.conf.
num-threads: ${threads}
rrset-cache-slabs: ${slabs}
msg-cache-slabs: ${slabs}
infra-cache-slabs: ${slabs}
key-cache-slabs: ${slabs}
rrset-cache-size: ${rrset_cache_mb}m
msg-cache-size: ${msg_cache_mb}m
key-cache-size: ${key_cache_mb}m
neg-cache-size: ${neg_cache_mb}m
EOT

echo "Generated /opt/unbound/etc/unbound/dynamic.conf"

# Create var directory for trust anchor
mkdir -p /opt/unbound/etc/unbound/var && \
chmod 700 /opt/unbound/etc/unbound/var && \
chown _unbound:_unbound /opt/unbound/etc/unbound/var

# Update DNSSEC root trust anchor (exit codes: 0=unchanged, 1=updated, other=error)
/opt/unbound/sbin/unbound-anchor -a /opt/unbound/etc/unbound/var/root.key
anchor_exit=$?
if [ "$anchor_exit" -gt 1 ]; then
    echo "WARNING: unbound-anchor failed with exit code ${anchor_exit}" >&2
fi

echo "==================================================================="
echo "Starting Unbound DNS Server..."
echo "==================================================================="

# Start Unbound in foreground
exec /opt/unbound/sbin/unbound -d -c /opt/unbound/etc/unbound/unbound.conf
